In [2]:
#!pip install pydataset
#https://www.cs.toronto.edu/~delve/data/boston/bostonDetail.html

Collecting pydataset
  Downloading https://files.pythonhosted.org/packages/4f/15/548792a1bb9caf6a3affd61c64d306b08c63c8a5a49e2c2d931b67ec2108/pydataset-0.2.0.tar.gz (15.9MB)
Requirement already satisfied: pandas in c:\users\administrator\anaconda3\lib\site-packages (from pydataset) (0.23.4)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\users\administrator\anaconda3\lib\site-packages (from pandas->pydataset) (2.7.5)
Requirement already satisfied: pytz>=2011k in c:\users\administrator\anaconda3\lib\site-packages (from pandas->pydataset) (2018.7)
Requirement already satisfied: numpy>=1.9.0 in c:\users\administrator\anaconda3\lib\site-packages (from pandas->pydataset) (1.15.4)
Requirement already satisfied: six>=1.5 in c:\users\administrator\anaconda3\lib\site-packages (from python-dateutil>=2.5.0->pandas->pydataset) (1.12.0)
Building wheels for collected packages: pydataset
  Running setup.py bdist_wheel for pydataset: started
  Running setup.py bdist_wheel for pydataset: finished with status 'done'
  Stored in directory: C:\Users\Administrator\AppData\Local\pip\Cache\wheels\fe\3f\dc\5d02ccc767317191b12d042dd920fcf3432fab74bc7978598b
Successfully built pydataset
Installing collected packages: pydataset
Successfully installed pydataset-0.2.0

In [1]:
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn import metrics
import pandas as pd
import numpy as np

In [2]:
from pydataset import data
# Get the housing data
df = data('Housing')
#df.head().values
df.head()

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
1,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
2,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
3,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
4,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
5,61000.0,6360,2,1,1,yes,no,no,no,no,0,no

In [7]:
# label 'yes' and 'no'
d = dict(zip(['no', 'yes'], range(0,2)))
for i in zip(df.dtypes.index, df.dtypes):
    print(i)
    if str(i[1]) == 'object':
        df[i[0]] = df[i[0]].map(d)

('price', dtype('int8'))
('lotsize', dtype('int64'))
('bedrooms', dtype('int64'))
('bathrms', dtype('int64'))
('stories', dtype('int64'))
('driveway', dtype('int64'))
('recroom', dtype('int64'))
('fullbase', dtype('int64'))
('gashw', dtype('int64'))
('airco', dtype('int64'))
('garagepl', dtype('int64'))
('prefarea', dtype('int64'))

In [4]:
df

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
1,42000.0,5850,3,1,2,1,0,1,0,0,1,0
2,38500.0,4000,2,1,1,1,0,0,0,0,0,0
3,49500.0,3060,3,1,1,1,0,0,0,0,0,0
4,60500.0,6650,3,1,2,1,1,0,0,0,0,0
5,61000.0,6360,2,1,1,1,0,0,0,0,0,0
6,66000.0,4160,3,1,1,1,1,1,0,1,0,0
7,66000.0,3880,3,2,2,1,0,1,0,0,2,0
8,69000.0,4160,3,1,3,1,0,0,0,0,0,0
9,83800.0,4800,3,1,1,1,1,1,0,0,0,0
10,88500.0,5500,3,2,4,1,1,0,0,1,1,0
11,90000.0,7200,3,2,1,1,0,1,0,1,3,0
12,30500.0,3000,2,1,1,0,0,0,0,0,0,0
13,27000.0,1700,3,1,2,1,0,0,0,0,0,0
14,36000.0,2880,3,1,1,0,0,0,0,0,0,0
15,37000.0,3600,2,1,1,1,0,0,0,0,0,0
16,37900.0,3185,2,1,1,1,0,0,0,1,0,0
17,40500.0,3300,3,1,2,0,0,0,0,0,1,0
18,40750.0,5200,4,1,3,1,0,0,0,0,0,0
19,45000.0,3450,1,1,1,1,0,0,0,0,0,0
20,45000.0,3986,2,2,1,0,1,1,0,0,1,0
21,48500.0,4785,3,1,2,1,1,1,0,1,1,0
22,65900.0,4510,4,2,2,1,0,1,0,0,0,0
23,37900.0,4000,3,1,2,1,0,0,0,1,0,0
24,38000.0,3934,2,1,1,1,0,0,0,0,0,0
25,42000.0,4960,2,1,1,1,0,0,0,0,0,0
26,42300.0,3000,2,1,2,1,0,0,0,0,0,0
27,43500.0,3800,2,1,1,1,0,0,0,0,0,0
28,44000.0,4960,2,1,1,1,0,1,0,1,0,0
29,44500.0,3000,3,1,1,0,0,0,0,1,0,0
30,44900.0,4500,3,1,2,1,0,0,0,1,0,0
31,45000.0,3500,2,1,1,0,0,1,0,0,0,0
32,48000.0,3500,4,1,2,1,0,0,0,1,2,0
33,49000.0,4000,2,1,1,1,0,0,0,0,0,0
34,51500.0,4500,2,1,1,1,0,0,0,0,0,0
35,61000.0,6360,2,1,2,1,0,0,0,0,0,0
36,61000.0,4500,2,1,1,1,0,0,0,1,2,0
37,61700.0,4032,2,1,1,1,0,1,0,0,0,0
38,67000.0,5170,3,1,4,1,0,0,0,1,0,0
39,82000.0,5400,4,2,2,1,0,0,0,1,2,0
40,54500.0,3150,2,2,1,0,0,1,0,0,0,0
41,66500.0,3745,3,1,2,1,0,1,0,0,0,0
42,70000.0,4520,3,1,2,1,0,1,0,1,0,0
43,82000.0,4640,4,1,2,1,0,0,0,0,1,0
44,92000.0,8580,5,3,2,1,0,0,0,0,2,0
45,38000.0,2000,2,1,2,1,0,0,0,0,0,0
46,44000.0,2160,3,1,2,0,0,1,0,0,0,0
47,41000.0,3040,2,1,1,0,0,0,0,0,0,0
48,43000.0,3090,3,1,2,0,0,0,0,0,0,0
49,48000.0,4960,4,1,3,0,0,0,0,0,0,0
50,54800.0,3350,3,1,2,1,0,0,0,0,0,0
51,55000.0,5300,5,2,2,1,0,0,0,0,0,0
52,57000.0,4100,4,1,1,0,0,1,0,0,0,0
53,68000.0,9166,2,1,1,1,0,1,0,1,2,0
54,95000.0,4040,3,1,2,1,0,1,1,0,1,0
55,38000.0,3630,3,3,2,0,1,0,0,0,0,0
56,25000.0,3620,2,1,1,1,0,0,0,0,0,0
57,25245.0,2400,3,1,1,0,0,0,0,0,0,0
58,56000.0,7260,3,2,1,1,1,1,0,0,3,0
59,35500.0,4400,3,1,2,1,0,0,0,0,0,0
60,30000.0,2400,3,1,2,1,0,0,0,0,0,0
61,48000.0,4120,2,1,2,1,0,0,0,0,0,0
62,48000.0,4750,2,1,1,1,0,0,0,0,0,0
63,52000.0,4280,2,1,1,1,0,0,0,1,2,0
64,54000.0,4820,3,1,2,1,0,0,0,0,0,0
65,56000.0,5500,4,1,2,1,1,1,0,0,0,0
66,60000.0,5500,3,1,2,1,0,0,0,1,0,0
67,60000.0,5040,3,1,2,1,0,1,0,1,0,0
68,67000.0,6000,2,1,1,1,0,1,0,1,1,0
69,47000.0,2500,2,1,1,0,0,0,0,1,0,0
70,70000.0,4095,3,1,2,0,1,1,0,1,0,0
71,45000.0,4095,2,1,1,1,0,0,0,0,2,0
72,51000.0,3150,3,1,2,1,0,1,0,0,0,0
73,32500.0,1836,2,1,1,0,0,1,0,0,0,0
74,34000.0,2475,3,1,2,1,0,0,0,0,0,0
75,35000.0,3210,3,1,2,1,0,1,0,0,0,0
76,36000.0,3180,3,1,1,0,0,0,0,0,0,0
77,45000.0,1650,3,1,2,0,0,1,0,0,0,0
78,47000.0,3180,4,1,2,1,0,1,0,1,0,0
79,55000.0,3180,2,2,1,1,0,1,0,0,2,0
80,63900.0,6360,2,1,1,1,0,1,0,1,1,0
81,50000.0,4240,3,1,2,1,0,0,0,1,0,0
82,35000.0,3240,2,1,1,0,1,0,0,0,1,0
83,50000.0,3650,3,1,2,1,0,0,0,0,0,0
84,43000.0,3240,3,1,2,1,0,0,0,0,2,0
85,55500.0,3780,2,1,2,1,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
462,49000.0,2145,3,1,3,1,0,0,0,0,0,1
463,49000.0,2610,3,1,2,1,0,1,0,0,0,1
464,49000.0,1950,3,2,2,1,0,1,0,0,0,1
465,49500.0,2145,3,1,3,1,0,0,0,0,0,1
466,52000.0,2275,3,1,3,1,0,0,1,1,0,1
467,54000.0,2856,3,1,3,1,0,0,0,0,0,1
468,55000.0,2015,3,1,2,1,0,1,0,0,0,1
469,55000.0,2176,2,1,2,1,1,0,0,0,0,1
470,56000.0,2145,4,2,1,1,0,1,0,0,0,1
471,60000.0,2145,3,1,3,1,0,0,0,0,1,1
472,60500.0,2787,3,1,1,1,0,1,0,0,0,1
473,50000.0,9500,3,1,2,1,0,0,0,0,3,1
474,64900.0,4990,4,2,2,1,1,1,0,0,0,1
475,93000.0,6670,3,1,3,1,0,1,0,0,0,1
476,85000.0,6254,4,2,1,1,0,1,0,0,1,1
477,61500.0,10360,2,1,1,1,0,0,0,0,1,1
478,88500.0,5500,3,2,1,1,1,1,0,0,2,1
479,88000.0,5450,4,2,1,1,0,1,0,1,0,1
480,89000.0,5500,3,1,3,1,0,0,0,0,1,1
481,89500.0,6000,4,1,3,1,1,1,0,0,0,1
482,95000.0,5700,3,1,1,1,1,1,0,1,2,1
483,95500.0,6600,2,2,4,1,0,1,0,0,0,1
484,51500.0,4000,2,1,1,1,0,0,0,0,0,1
485,62900.0,4880,3,1,1,1,0,0,0,0,2,1
486,118500.0,4880,4,2,2,1,0,0,0,1,1,1
487,42900.0,8050,2,1,1,1,0,0,0,0,0,0
488,44100.0,8100,2,1,1,1,0,0,0,0,1,0
489,47000.0,5880,3,1,1,1,0,0,0,0,1,0
490,50000.0,5880,2,1,1,1,0,0,0,0,0,0
491,50000.0,12944,3,1,1,1,0,0,0,0,0,0
492,53000.0,6020,3,1,1,1,0,0,0,0,0,0
493,53000.0,4050,2,1,1,1,0,0,0,0,0,0
494,54000.0,8400,2,1,1,1,0,0,0,0,1,0
495,58500.0,5600,2,1,1,1,0,0,0,1,0,0
496,59000.0,5985,3,1,1,1,0,1,0,0,0,0
497,60000.0,4500,3,1,1,1,0,1,0,0,0,0
498,62900.0,4920,3,1,2,1,0,0,0,0,1,0
499,64000.0,8250,3,1,1,1,0,0,0,0,0,0
500,65000.0,8400,4,1,4,1,0,0,0,0,3,0
501,67900.0,6440,2,1,1,1,0,0,0,1,3,0
502,68500.0,8100,4,1,4,1,0,1,0,1,2,0
503,70000.0,6720,3,1,1,1,0,0,0,0,0,0
504,70500.0,5948,3,1,2,1,0,0,0,1,0,0
505,71500.0,8150,3,2,1,1,1,1,0,0,0,0
506,71900.0,4800,2,1,1,1,1,1,0,0,0,0
507,75000.0,9800,4,2,2,1,1,0,0,0,2,0
508,75000.0,8520,3,1,1,1,0,0,0,1,2,0
509,87000.0,8372,3,1,3,1,0,0,0,1,2,0
510,64000.0,4040,3,1,2,1,0,0,0,0,1,0
511,70000.0,4646,3,1,2,1,1,1,0,0,2,0
512,47500.0,4775,4,1,2,1,0,0,0,0,0,0
513,62600.0,4950,4,1,2,1,0,0,0,1,0,0
514,66000.0,5010,3,1,2,1,0,1,0,0,0,0
515,58900.0,6060,2,1,1,1,0,1,0,0,1,0
516,53000.0,3584,2,1,1,1,0,0,1,0,0,0
517,95000.0,6000,3,2,3,1,1,0,0,1,0,0
518,96500.0,6000,4,2,4,1,0,0,0,1,0,0
519,101000.0,6240,4,2,2,1,0,0,0,1,1,0
520,102000.0,6000,3,2,2,1,1,0,0,0,1,0
521,103000.0,7680,4,2,4,1,1,0,0,1,1,0
522,105000.0,6000,4,2,4,1,1,0,0,1,1,0
523,108000.0,6000,4,2,4,1,0,0,0,1,1,0
524,110000.0,6000,4,2,4,1,0,0,0,0,2,0
525,113000.0,6000,4,2,4,1,0,0,0,1,1,0
526,120000.0,7475,3,2,4,1,0,0,0,1,2,0
527,105000.0,5150,3,2,4,1,0,0,0,1,2,0
528,106000.0,6325,3,1,4,1,0,0,0,1,1,0
529,107500.0,6000,3,2,4,1,0,0,0,1,1,0
530,108000.0,6000,3,2,3,1,0,0,0,1,0,0
531,113750.0,6000,3,1,4,1,1,0,0,1,2,0
532,120000.0,7000,3,1,4,1,0,0,0,1,2,0
533,70000.0,12900,3,1,1,1,0,0,0,0,2,0
534,71000.0,7686,3,1,1,1,1,1,1,0,0,0
535,82000.0,5000,3,1,3,1,0,0,0,1,0,0
536,82000.0,5800,3,2,4,1,0,0,0,1,0,0
537,82500.0,6000,3,2,4,1,0,0,0,1,0,0
538,83000.0,4800,3,1,3,1,0,0,0,1,0,0
539,84000.0,6500,3,2,3,1,0,0,0,1,0,0
540,85000.0,7320,4,2,2,1,0,0,0,0,0,0
541,85000.0,6525,3,2,4,1,0,0,0,0,1,0
542,91500.0,4800,3,2,4,1,1,0,0,1,0,0
543,94000.0,6000,3,2,4,1,0,0,0,1,0,0
544,103000.0,6000,3,2,4,1,1,0,0,1,1,0
545,105000.0,6000,3,2,2,1,1,0,0,1,1,0
546,105000.0,6000,3,1,2,1,0,0,0,1,1,0

In [5]:
# 가격의 범위를 정해준듯 ????

for i, j in enumerate(np.unique(pd.qcut(df['price'], 3))):
    print(i, j)

0 (24999.999, 53000.0]
1 (53000.0, 74500.0]
2 (74500.0, 190000.0]

In [6]:
df['price'] = pd.qcut(df['price'], 3, labels=['0', '1', '2']).cat.codes
y = df['price'] 
X = df.drop('price', 1)